### ISSUE TITLE
StackOverFlow while `parascopy table`

### ISSUE THREAD

**Issue by mr-eyes** [tprodanov/parascopy#14]
I am trying to build a homology table for the CHM13 T2T, and I used these commands:

```sh

wget https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13v2.0_SD.bed

parascopy pretable -f chm13v2.0.fa -o pretable_chm13v2.bed.gz -@ 64 -R chm13v2.0_SD.bed # succeed
parascopy table -i pretable_chm13v2.bed.gz -f chm13v2.0.fa -o table_chm13v2.bed.gz -@ 64 -R chm13v2.0_SD.bed # failed
```

The `pretable` succeeded, while the `table` failed:

```
0:00:01.9  ERROR:
Traceback (most recent call last):
  File "/path_to_parascopy/parascopy/combine_table.py", line 434, in _save_component_wrapper
    return _save_component(*tup)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path_to_parascopy/parascopy/combine_table.py", line 418, in _save_component
    comb_dupl = combine_segments(segments, aln_fun)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path_to_parascopy/parascopy/inner/duplication.py", line 975, in combine_segments
    new_cigar = _move_everything_left(new_cigar, shift1, seq1, shift2, seq2)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path_to_parascopy/parascopy/inner/duplication.py", line 842, in _move_everything_left
    pos2 += length
OverflowError: Python integer -181999855 out of bounds for uint32
```

**Comment by tprodanov** [comment]
Hi there! Sorry for such a long response, but we finally fixed the issue, it should work now. Please write us if you encounter any other errors!
